baseurl = "/"
title = "Andrew's Blog"
theme = "ghostwriter"
languageCode = "en-gb"
copyright = "Andrew Peacock"
disqusShortname = "andrewpeacock"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Andrew Peacock's Blog"
    github = "https://github.com/LuckVintage"
    twitter = "https://twitter.com/AndrewPeacockUK"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, 2 Jan, 2006"
    readingTime = "true"
    readingTimeText = "Estimated reading time:"
    rss = true

[Permalinks]
    post = "/:filename/"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 2